### ISSUE TITLE
upgrade platformio is not recommended

### ISSUE THREAD

**Issue by tprelog** [tprelog/iocage-esphome#1]
@CyanoFresh

While compiling new firmware right after a fresh install, I see a message saying there is an upgrade available for platformio so I thought I would just run platformio upgrade during the install. 

Including this upgrade step prevents esphome from ever starting.

Also if I try to `pip3 install -U platformio` I get this message about a dependency conflict.
```bash
ERROR: esphome 1.14.3 has requirement platformio==4.0.3, but you'll have platformio 4.1.0 which is incompatible.
```
---
I asked about [this in the Home Assistant Form](https://community.home-assistant.io/t/do-i-need-to-upgrade-platformio-separately/169922?u=troy) -- it was suggested this

> Unless you had a reason to do it I wouldn’t worry. Esphome ships with specific version of many libraries and sometimes stuff gets incompatible if you try to use latest versions of tools

So am going to [revert these changes](https://github.com/tprelog/iocage-homeassistant/pull/8)

I think that by default, it is best to let the esphome dependency determine what  version of platformio should be installed. If a platformio upgrade is required, it will still happen automatically when the dependency version get bumped in esphome.

However, I will leave these abilities as separate functions that can be used independently if needed.

**Comment by CyanoFresh** [comment]
yep, by default is not necessary to upgrade platformio.

**Comment by tprelog** [comment]
I've commented out the lines to update/upgrade platformio by default. I'll add separate functions for this in the future
