### ISSUE TITLE
Compiling broken. Update to 1.14.4 needed.

### ISSUE THREAD

**Issue by alphazero1990** [tprelog/iocage-esphome#2]
They broke the compiling on the current version 1.14.3 just a few days ago. The new version 1.14.4 fixes that. I would request an update if possible, otherwise the plugin will remain unusable.

**Comment by tprelog** [comment]
@alphazero1990 

I'm currently not using esphome ( stuck on my list of "Things to get to" ) -- however I just installed plugin and was able to compile both `Generic ESP8266` and `Generic ESP32` without error.


I was able to find and restore a backup I had made shortly after creating the plugin. I restore the old version and I see that you may just need to update `esphome` -- This is already in the plugin but must be preformed from the console. ( esphome updates are not tied to "Update Plugin" in the FreeNAS UI )

You can use `ssh` if you'd like but this should work easily from the browser as well. From the Jails page on FreeNAS --> Press SHELL to connect to the console. There is a simple menu, number `4` to upgrade.

![image](https://user-images.githubusercontent.com/35702532/84572172-5a365100-ad66-11ea-887e-aefe92de8d7a.png)

I did see an error at the end of the update process about a package not being installed ( sorry I forget the record the error ) however the suspect package was later installed correctly when I updated my test module that had been save from before. 

I was able to again compile both `Generic ESP8266` and `Generic ESP32` without error after updating esphome as shown in the image

**Comment by alphazero1990** [comment]
Yes it works! Thank you so much. I totally forgot it has a CLI UI and I missed the upgrade option completely as well. May I suggest a quick mention on how to upgrade in the ReadMe? For other people.

Do you have Paypal? Wanna buy you a coffee :D.

**Comment by tprelog** [comment]
>May I suggest a quick mention on how to upgrade in the ReadMe?

Absolutely! I'll leave this issue open to remind self :slightly_smiling_face: 

>Do you have Paypal? Wanna buy you a coffee

Thank you for your consideration but I haven't done much here. If you like using ESPHome please consider making a contribution [directly to the project ](https://esphome.io/guides/supporters.html)
