### ISSUE TITLE
Plugin not working anymore

### ISSUE THREAD

**Issue by pasiz** [tprelog/iocage-esphome#4]
Toolchain not workin after plugin installation.

```
NFO Reading configuration /var/db/esphome/testnode.yaml...
INFO Generating C++ source...
INFO Compiling app...
INFO Running:  platformio run -d /var/db/esphome/testnode
Processing testnode (board: nodemcuv2; framework: arduino; platform: espressif8266@2.6.2)
--------------------------------------------------------------------------------
PackageManager: Installing toolchain-xtensa @ ~2.40802.191122
Error: Could not find a version that satisfies the requirement '~2.40802.191122' for your system 'freebsd_amd64'
```

**Comment by tprelog** [comment]
@CyanoFresh -- Do you have any ideas? I'm not having much luck with Google.

I was able to modify an existing `.platformio/packages/toolchain-xtensa/package.json`, simply changing the version to `2.40802.191122` seemed to work but it's probably not gonna be that simple.

---

I've tried building https://github.com/trombik/freebsd-ports-xtensa-lx106-elf/tree/master/devel/xtensa-lx106-elf and using https://github.com/trombik/platformio-freebsd-toolchain-xtensa to setup the toolchain for platformio.

I got it to start compiling but fails when it begins linking firmware--> https://paste.ubuntu.com/p/Rvfbq5g8S3/

**Comment by CyanoFresh** [comment]
@tprelog sorry, don't have a freebsd right now, but trombik replied to my previous issue https://github.com/platformio/platform-espressif32/issues/269#issuecomment-689932441 
maybe you can get find something there

**Comment by TotoBlues** [comment]
Hi
@CyanoFresh i followed this https://github.com/platformio/platform-espressif32/issues/269 to install toolchain-xtensa32. I've tried so many ways to download multiple repo 
https://github.com/trombik/toolchain-xtensa32/releases/tag/0.2.0
https://github.com/trombik/platformio-freebsd-toolchain-xtensa32
https://github.com/esphome/esphome-docker-base/tags
https://bintray.com/platformio/tool-packages/toolchain-xtensa-freebsd_amd64#files
and so on...
but the copiler always fail to
![image](https://user-images.githubusercontent.com/15133731/95859011-3dcf1300-0d5e-11eb-813e-eaf2a3916f1d.png)

Maybe i put all this files in the bad path ?? (All tries was made on fresh install plugin)

**Comment by tprelog** [comment]
I haven't had much time to further learn / trouble shoot why this isn't working when I compile it from trombik's port.

The following workaround seems to be working for now.

```
pkg install curl
su - esphome
curl -o /tmp/toolchain-xtensa.tar.gz -OL https://github.com/tprelog/iocage-esphome/raw/toolchain-hack/toolchains/toolchain-xtensa-freebsd_amd64-2.40802.191122-HACK.tar.gz
tar -x -C .platformio/packages -f /tmp/toolchain-xtensa.tar.gz
```

**Comment by TotoBlues** [comment]
If it can help someone I asked on platformIO for some help and this is the answer : 
https://community.platformio.org/t/platformio-on-freebsd/16472/2?u=totoblues

**Comment by tprelog** [comment]
Thanks for the link @TotoBlues 

So seems like we can just bump the version? The workaround I mentioned above is using the same solution...
I have simply taken an existing copy of the `toolchain-xtensa` and set `"version": "2.40802.191122"` in the `package.json`

I've added this to the `post_install.sh` as well, so compiling should now work again for clean installs of this plugin.
