### ISSUE TITLE
Impossible to use wget

### ISSUE THREAD

**Issue by TotoBlues** [tprelog/iocage-esphome#5]
Hi guys trying your plugins for esphome and i got some problem.

freeNAS version: 11.3-U4.1
esphome version: 1.15.2

I got an error while using wget. I got other jails and wget works on all except esphome.
and the error is : 
![image](https://user-images.githubusercontent.com/15133731/95856013-abc50b80-0d59-11eb-8dd0-17f7808b3e42.png)

thanks for help

**Comment by TotoBlues** [comment]
Hi @tprelog thanks for answer ! 
I have one jail on version 11.4-RELEASE-p4 by installing it manually from GUI. 
And for others jails (like homeassistant plugin) I have no problem with wget:
![image](https://user-images.githubusercontent.com/15133731/96002082-04b7a100-0e39-11eb-84f8-523c7002355a.png)
All my jails is on the same RELEASE (11.3-RELEASE-p14) except the one i speak of earlier.

Hope this can help

**Comment by TotoBlues** [comment]
I just use curl so don't be sorry for that ! Thanks for all the great work you do with all these plugins !

**Comment by TotoBlues** [comment]
Thanks for your concern ! Maybe I have to update to TrueCore for freeBSD 12.0 so ... Do you know if the plugins script you made will work on it ?

**Comment by tprelog** [comment]
yea, as far as I know. I switched to TrueNAS Core about 2 months ago. All my plugins installed without issue. I just tested esphome again. I can confirm it successfully installed and now includes the `toolchain-xtensa` workaround from issue 4.

To be honest though, I only use Home Assistant, Mosquitto and Gogs on a regular basis, so with the other plugins, I've really only tested the installation. I'm not sure if there are any issues past that

**Comment by TotoBlues** [comment]
Is there a way to upgrade freebsd version of plugins that was installed in 11.3 version ?

**Comment by tprelog** [comment]
I haven't really tested this but the following should work.

```
iocage upgrade $JAIL_ NAME
```
 Even though it needs run from the console, it will still create a snapshot. If there are any issues , just roll back the snapshot and let me know

**Comment by TotoBlues** [comment]
@tprelog working like a charm thanks for the tips
