### ISSUE TITLE
Not an issue - esphome usb in jail discussion

### ISSUE THREAD

**Issue by TotoBlues** [tprelog/iocage-esphome#6]
Hi, 
I tried to connect usb to the dashboard from inside the jail but the usb doesn't show up. I think it's just a right access issue.
I have my usb detected on the jail thanks to the devfs.rules preset on freeNAS. 

The screen show the settings i put on the jail, where to find the devfs.rule (preset by freeNAS) and the error i faced launching a "esphome run" manually.
![image](https://user-images.githubusercontent.com/15133731/96037769-8a057a80-0e66-11eb-8497-04dd5241796d.png)

Can you take a look at it ?

**Comment by tprelog** [comment]
Does adding the `esphome` user to the `uucp` group help?
```
pw group mod uucp -m esphome
```

**Comment by TotoBlues** [comment]
I got this error : 
![image](https://user-images.githubusercontent.com/15133731/96120668-2d9a6d80-0eef-11eb-9f11-46d532d02b4b.png)
I will look if i got something on the web
