### ISSUE TITLE
url toolchain freebsd ist error 404

### ISSUE THREAD

**Issue by duffel90** [tprelog/iocage-esphome#8]
Is there a new url for the compiled toolchain?

**Comment by tprelog** [comment]
Unfortunately not. I've tried to compile it myself, but had no luck.

**Comment by tprelog** [comment]
@duffel90

Hey I managed to get the toolchain compiled - Are you still trying to use this plugin?

**Comment by tprelog** [comment]
I've uploaded the pre-compiled toolchains to a detached branch. Here's some quick instructions to manually update

Log into the jail and install some new dependencies
```bash
iocage console $JAIL_NAME
# Press 1 to exit the menu
pkg install -y hash rust
```

Download and install the pre-compiled toolchains for ESP8266 and ESP32
```bash
#  toolchain-xtensa - ESP8266
fetch https://github.com/tprelog/iocage-esphome/raw/toolchains/toolchains/toolchain-xtensa-FreeBSD.12.amd64-2.40802.191122.pkg
pkg install -y toolchain-xtensa-FreeBSD.12.amd64-2.40802.191122.pkg

# toolchain-xtensa32 - ESP32
fetch https://github.com/tprelog/iocage-esphome/raw/toolchains/toolchains/toolchain-xtensa32-FreeBSD.12.amd64-2.50200.0.pkg
pkg install -y toolchain-xtensa32-FreeBSD.12.amd64-2.50200.0.pkg
```

Now switch to the esphome user and remove the existing `.platformio/packages` directory
```bash
su - esphome
rm -rf ~/.platformio/packages
```

Next create an empty `.platformio/packages` directory and `cd` into it
```bash
mkdir -p ~/.platformio/packages
cd ~/.platformio/packages
```

Finally create the links to the installed toolchains
```bash
#  toolchain-xtensa
ln -s /usr/local/esp-quick-toolchain-gcc48/xtensa-lx106-elf .

#  toolchain-xtensa32
ln -s /usr/local/xtensa-esp32-elf-idf3 toolchain-xtensa32
```

**Comment by duffel90** [comment]
thx @tprelog I will try it later and give feedback  ^^

**Comment by duffel90** [comment]
@tprelog GREAT WORK. working also with 12.2-RELEASE

the only error i get is:
Library Manager: Installing Hash
Warning! Could not find the package with 'Hash' requirements for your system 'freebsd_amd64'

But it looks like that it doesn't metter for me.

**Comment by tprelog** [comment]
@duffel90  - I noticed the same error

```
ibrary Manager: Installing Hash
Warning! Could not find the package with 'Hash' requirements for your system 'freebsd_amd64'
```

Here's something strange, and seems to be a work around...

Create a minimal config for an ESP8266 device, then compile it's firmware. You may notice this will find and use the system version `hash` that was installed above, using `pkg`.

Now, when you compile the firmware for ESP32 devices, you may notice the system version `hash` is being used.
